### ISSUE TITLE
Request - move INFO events to debug.log

### ISSUE THREAD

**Issue by bessiq** [Darkhax-Minecraft/Never-Enough-Candy#5]
NeverEnoughCandy-1.16.3-2.0.1.jar

`[16Oct2020 17:32:23.887] [Server thread/INFO] [STDOUT/]: [net.darkhax.neverenoughcandy.NeverEnoughCandy:onLivingDrops:77]: hi BatEntity['Bat'/103889, l='ServerLevel[New World]', x=-317.08, y=18.36, z=184.91]
`

Just makes the latest.log a little...busy. 😊 🍬

**Comment by Darkhax** [comment]
Thanks for pointing this out, this actually shouldn't be included at all. Will fix shortly.

**Comment by Darkhax** [comment]
This issue is now fixed on the 1.16.4 version.
